### ISSUE TITLE
Reset _oldAttributes after afterSave.

### ISSUE THREAD

**Issue by vaso2** [yiisoft/active-record#1]
### What steps will reproduce the problem?
Somewhere in controller etc.
```
// For example, start === 10, end === 18
$model->start = 12;
$model->save();
```
`EVENT_AFTER_UPDATE` handler

```
if ($this->isAttributeChanged("start") || $this->isAttributeChanged("end")) {
  echo "Interval changed from {$this->getOldAttribute("start")} - {$this->getOldAttribute("end")} to {$this->start} - {$this->end}";
}
```
### What is the expected result?
Interval changed from 10 - 18 to 12 - 18
### What do you get instead?
Nothing printed, old attributes were reset and `isAttributeChanged` returns false.
To make it happen I'll need to use array_key_exists('parent_id', $changedAttributes) many times, some constructs like `isset($changedAttributes['start']) ? $changedAttributes['start'] : $this->start` etc. All that make code much less readable and introduces lots of duplicated code.

### Additional info
Problem is here
https://github.com/yiisoft/active-record/blob/8200ac5a3acc3b20f3032ecd39b9d00b3aa34b88/src/BaseActiveRecord.php#L822
There were lots of such issues before, like [this](https://github.com/yiisoft/yii2/issues/4086) and [this](https://github.com/yiisoft/yii2/issues/13472). And while it's possible to use current logic or tweak it yourself, I think a proposed approach is more straightforward.

**Comment by SamMousa** [comment]
I think this is a misunderstanding.

`oldAttributes` is used to track dirty attributes. Dirty means it the AR model is not in sync with the underlying storage.

After an update we just synced them so the attributes are no longer dirty.

"Fixing" this would cause bugs like repeated `save()` will send duplicate unneeded queries to the db and other things like that...

**Comment by samdark** [comment]
At least we need to rename property from `old` to `dirty`.

**Comment by samdark** [comment]
But overall, actual enhancement allowing what's proposed sounds useful.

**Comment by samdark** [comment]
Yes. It's useful enough to be in the core, I think.
