### ISSUE TITLE
Documentation incorrect (parse error)

### ISSUE THREAD

**Issue by Mister-42** [yiisoft/active-record#101]
### What steps will reproduce the problem?
Use code [from documentation](https://github.com/yiisoft/active-record/blob/5a7f24fc97926fb1ce48899f8dcb49551d1fdc6e/src/ActiveQuery.php#L74)
```
<?php
$customerQuery = ActiveQuery(new Customer::class, $db);
$query = $customerQuery->with('orders')->asArray()->all();
```

### What is the expected result?
Working code

### What do you get instead?
<b>Parse error</b>:  syntax error, unexpected 'class' (T_CLASS), expecting variable (T_VARIABLE) or '$' in <b>[...][...]</b> on line <b>2</b>

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 7.4.11
| Operating system | Debian 10

**Comment by terabytesoftw** [comment]
You want to do a pr by correcting the error.
