### ISSUE TITLE
Add factory to BaseActiveRecord.

### ISSUE THREAD

**Issue by mj4444ru** [yiisoft/active-record#109]
Maybe you should add a factory to BaseActiveRecord similar to ActiveQuery?
It is necessary to pass the factory as recursively as the connection, otherwise when receiving objects from the list, we lose the ability to create related objects from the factory.

https://github.com/yiisoft/active-record/blob/3349e337b05f82e166c9b6499c57616061e3082c/src/BaseActiveRecord.php#L62

https://github.com/yiisoft/active-record/blob/3349e337b05f82e166c9b6499c57616061e3082c/src/ActiveQuery.php#L109

**Comment by terabytesoftw** [comment]
What would be the use case for the factory in `BaseActiveRecord::class`

Thks.

**Comment by mj4444ru** [comment]
https://github.com/yiisoft/active-record/blob/3349e337b05f82e166c9b6499c57616061e3082c/src/ActiveQuery.php#L1090-L1094

requires a factory

https://github.com/yiisoft/active-record/blob/3349e337b05f82e166c9b6499c57616061e3082c/src/ActiveQuery.php#L109

```php
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getImages()
    {
        return $this->hasMany(\app\models\Image::className(), ['game_id' => 'id'])->inverseOf('game');
    }
```

This code will create an ActiveQuery without a factory. But even if we create ActiveQuery through `new ActiveQuery`, we still have nowhere to get an AR factory for ActiveQuery.

**Comment by terabytesoftw** [comment]
Is that you can `map`, `create` and change the `AR connection` without having to inject the factory in BaseActiveRecord :: class

**Comment by terabytesoftw** [comment]
@samdark @yiiliveext What do you think?

Thank you.

**Comment by mj4444ru** [comment]
You made a factory, but you didn't make it fully usable. I am not suggesting to make the factory mandatory, I suggest passing it recursively, otherwise any meaning in it is lost.

For example, I suggest:

https://github.com/yiisoft/active-record/blob/3349e337b05f82e166c9b6499c57616061e3082c/src/BaseActiveRecord.php#L942-L949

replaced to:

```php
    public function instantiateQuery(): ActiveQueryInterface
    {
        if ($this->db->getDriverName() === 'redis') {
            return new RedisActiveQuery(static::class, $this->db, $this->arFactory);
        }

        return new ActiveQuery(static::class, $this->db, $this->arFactory);
    }
```

By the way, here's another improvement.

https://github.com/yiisoft/active-record/blob/3349e337b05f82e166c9b6499c57616061e3082c/src/BaseActiveRecord.php#L248-L257

replaced to:

```php
    protected function createRelationQuery(string $arClass, array $link, bool $multiple): ActiveQueryInterface
    {
        return $this->instantiateQuery()->primaryModel($this)->link($link)->multiple($multiple);
    }
```

**Comment by terabytesoftw** [comment]
Excellent thanks for your suggestions.
