### ISSUE TITLE
Avoiding overwriting andWhere()/orWhere() with where() in ActiveQuery when scoping data

### ISSUE THREAD

**Issue by YasserHassan** [yiisoft/active-record#12]
Although the result of using `where()` after `andWhere()` or `orWhere()` is known and documented, still it's one of the vulnerable areas that could easily fall through the cracks especially by new team members. It's easy to use `where()` in a child class to result in removing user scoping in the parent class and expose sensitive data.

To enhance this area, I'm suggesting the introduction of new method called `alwaysWhere()` (or `fixedWhere()` or `scopeWhere()` or `mustWhere()` ...etc) with the same signature of `where()` but its condition is not affected by `where()`, `andWhere()`, or `orWhere()`. Its condition would always be added to the `WHERE` condition in the resulting SQL statement. Taking this further, a parameter like `accumulate` could be used ( `where($condition, $accumulate = true)` ) so by default, any additional use of `alwaysWhere()` in the application will lead to adding the new condition to the old one unless `accumulate` is explicitly set to `false` by the developer to overwrite the scoping condition.

**Comment by mtangoo** [comment]
I think that will better be alleviated by making it clear in documentation than what you are suggesting.

User have to know how he shouldn't use where,  and having a note or a warning should suffice.

I don't believe it's necessary.

If it's really that necessary, which I don't believe it is,  then adding what you are explaining as an example or even better adding to Yii cookbook.
