### ISSUE TITLE
Join Multiple Databases

### ISSUE THREAD

**Issue by andryluthfi** [yiisoft/active-record#120]
I used Yii3 for my application with Active Record. I have done connect to my database, but I have problem with multiple connections database. In Yii2 I can doo that, but I don't know how to setup in active record Yii3.

**Comment by samdark** [comment]
Do you need a cross-database JOIN?

**Comment by andryluthfi** [comment]
HI @samdark 

> Do you need a cross-database JOIN?

Yes, to answer your question.

To make it clear, I have two tables in different databases which are member_access in database A and user in database B.
So I manage to solve this with explicitly append database name to `tableName()` function like this in model that connected another database.

```php
    /**
     * @return string
     */
    public function tableName(): string
    {
        return '{{another_database.user}}';
    }
```

I just want to make sure it works in `joinWith()` and `$member->memberAccess->user->email`.

```php
        /**
         * @var Member $member
         */
        $member = $activeRecordFactory->createQueryTo(Member::class)
            ->andWhere(['user.email' => 'sample@mail.com'])
            ->joinWith(['memberAccess.user'])
            ->one();

        return $dataResponseFactory->createResponse([
            'ID' => $member->ID,
            'email' => $member->email,
            'memberAccess' => [
                'userID' => $member->memberAccess->userID,
                'user' => $member->memberAccess->user->email
            ]
        ]);
```

This solution works for me, Is there any alternative solutions?

**Comment by samdark** [comment]
I'm not aware of any. @terabytesoftw ?

**Comment by terabytesoftw** [comment]
The other way is to do it without the factory, passing the connection directly, or to see the structure of the tables and make a relation.

**Comment by terabytesoftw** [comment]
I am going to close the issue any other query you can write join telegram group: https://t.me/yii3en
