### ISSUE TITLE
Use getARInstance() in every ActiveRecord Instantiation

### ISSUE THREAD

**Issue by andryluthfi** [yiisoft/active-record#123]
I realize that the ActiveQuery class uses a function called `getARInstance()`

https://github.com/yiisoft/active-record/blob/75b09b1addf62e2fbcf064bc4d48f1b62c2f9c37/src/ActiveQuery.php#L1090-L1099

From the following code below

https://github.com/yiisoft/active-record/blob/75b09b1addf62e2fbcf064bc4d48f1b62c2f9c37/src/ActiveQuery.php#L602

It does not use the getARInstance() or instantiate via ARFactory. The effects of not using it causes the formed relation object to not pass through ARFactory, so we can't use the Dependency injection in ActiveRecord Model Constructor. 

Like the example shown below, we tried to inject `SomeInterface` to the constructor.

```php
class City extends ActiveRecord {
    /**
     * City constructor.
     * @param ConnectionInterface $db
     * @param SomeInterface $foo
     */
    public function __construct(ConnectionInterface $db, SomeInterface $foo)
    {
        parent::__construct($db);

        $this->foo = $foo;
    }
   
    public function getCountry() {
        return $this->hasOne(Country::class, ['ID' => 'countryID']);
    }
}
```

```php
class Country extends ActiveRecord {
    /**
     * Country constructor.
     * @param ConnectionInterface $db
     * @param SomeInterface $foo
     */
    public function __construct(ConnectionInterface $db, SomeInterface $foo)
    {
        parent::__construct($db);

        $this->foo = $foo;
    }
}
```

Therefore, only the `createAR()` function succeeded in the ActiveRecordFactory, but it isn't a relation that was used to create using `createQueryTo`.

For example

```php
$query = $activeRecordFactory->createQueryTo(City::class);
$city = $query->one();
$city->country;
```

It'll result in an error.

**Comment by terabytesoftw** [comment]
Thks, @andryluthfi the Pr I just did should resolve the issue, thanks for reporting it.
