### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by sagittaracc** [yiisoft/active-record#147]
### What steps will reproduce the problem?
run composer require yiisoft/active-record

### What is the expected result?
yiisoft/active-record got installed

### What do you get instead?
[InvalidArgumentException]
  Could not find a version of package yiisoft/active-record matching your min
  imum-stability (stable). Require it with an explicit version constraint all
  owing its desired stability.

### Additional info
composer.json
```
{
    "name": "test/sag",
    "require": {
        "yiisoft/active-record": "dev-master"
    }
}
```
Getting the follow:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires yiisoft/active-record dev-master -> satisfiable by yiisoft/active-record[dev-master].
    - yiisoft/active-record dev-master requires yiisoft/db ^3.0@dev -> found yiisoft/db[dev-master, 3.0.x-dev (alias of dev-master)] but it does not match your minimum-stability.

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 7.4.15
| Operating system | Windows

**Comment by Mister-42** [comment]
```
    "minimum-stability": "dev",
    "prefer-stable": true,
```

**Comment by sagittaracc** [comment]
Thank you!
