### ISSUE TITLE
Is it really necessary tableName as non static method?

### ISSUE THREAD

**Issue by Gerych1984** [yiisoft/active-record#192]
Good day everybody. In previous versions Yii `AR::tableName()` was a static method and it was conveniently. For example i using it for  some custom complex queries somewhere in console/cron tasks, as part of cache-key for save aggregate heavy data, in custom helpers etc. In current version we must pass `ActiveRecordFactory/ActiveRecord` for each same cases and create AR instance inside, but that instance may not be needed further or redundant refactor like `SomeHelper::someStaticMethod(add ActiveRecordFactory/ActiveRecord there)`. So - is it really necessary do it as non static? This method just return name of table and I can't think of case where needed `$this` inside. Thanks

**Comment by terabytesoftw** [comment]
Returning the table name statically won't hurt, plus it's an immutable method.
