### ISSUE TITLE
Can ActiveRecord implement the interface ArrayableInterface, like Yii2?

### ISSUE THREAD

**Issue by niqingyang** [yiisoft/active-record#272]
### What steps will reproduce the problem?

I overwrite the method toArray() in my Model, but when I use ArrayHelper::toArray() to convert the Model into an array, my overwritten toArray method is not called. I found that it's because ActiveRecord doesn't implement the interface ArrayableInterface

```php
/**
 *
 * @property int $id
 * @property string|null $name
 * @property string|null $phone
 */
class User extends ActiveRecord
{
    public function tableName(): string
    {
        return '{{%user}}';
    }

    public function toArray(): array
    {
        $item = parent::toArray();
        $item['demo'] = 'demo';
        return $item;
    }
}

$user = $arFactory->createAR(User::class);
$user->name = 'xxx';

$data = ArrayHelper::toArray($user);

echo $data['demo'];

```

### What is the expected result?

```
'demo'
```

### What do you get instead?

```
null
```

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 8.1
| Operating system | Windows 10

**Comment by terabytesoftw** [comment]
Thanks for reporting, you have time for a PR.
