### ISSUE TITLE
Missing ModelEvent.php in \yii\base

### ISSUE THREAD

**Issue by terabytesoftw** [yiisoft/active-record#28]
### What steps will reproduce the problem?
Error: Class 'yii\base\ModelEvent' not found in /home/domain.com/public_html/vendor/yiisoft/active-record/src/BaseActiveRecord.php:972

### What is the expected result?
ModelEvent represents the parameter needed by [[Model]] events.

### Additional info
Event.php in public function __construct(string $name, $target = null, array $params = []) no accept boolean field.

| Q                | A
| ---------------- | ---
| Yii version      | 3.0
| PHP version      | 7.1.23
| Operating system | Centos 7

**Comment by machour** [comment]
Being fixed in #27
