### ISSUE TITLE
Using `Class::AFTER` of `Class::after()`

### ISSUE THREAD

**Issue by FabrizioCaldarelli** [yiisoft/active-record#29]
> I'm not sure why most calls are not  `Class::AFTER` instead of the static function call 🤔 
> Could you enlighten me?
> 

_Originally posted by @machour in https://github.com/yiisoft/active-record/pull/27/threads/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMTQ4NjY3NDA1OnYy/unresolve_

In ActiveRecordSaveEvent, we need to pass extra data ( $insert and $changedAttributes ) to the event object.

https://github.com/FabrizioCaldarelli/active-record/blob/missing-models/src/ActiveRecordSaveEvent.php

So I would uniform syntax to trigger event, otherwise we could have some cases with ::CLASS and other with ClassName::eventName( args )

**Comment by FabrizioCaldarelli** [comment]
In ActiveRecordSaveEvent, we could need to pass extra data ( $insert and $changedAttributes ) to the event object.

So I would uniform syntax to trigger event, otherwise we could have some cases with ::CLASS and other with ClassName::eventName( args )

**Comment by rob006** [comment]
@FabrizioCaldarelli Why are you opening separate issues for PR's comments? Without context it is harder to understand what it is about.

**Comment by FabrizioCaldarelli** [comment]
Because I can't answer inside the PR. Maybe have not I the right to do it in PR ?

**Comment by machour** [comment]
ping me on slack so we can sort this out
closing issues

**Comment by rob006** [comment]
> Because I can't answer inside the PR. Maybe have not I the right to do it in PR ?

Weird. This is how it looks for me:

![9474728e](https://user-images.githubusercontent.com/5972388/50585936-a560ea80-0e77-11e9-9c7d-fdeabf3a3ad0.png)

Are you sure that some browser plugin does not hide this input?

@machour Please do not use Slack for any important discussion - some decision and discussions should be archived and easily accessible, and Slack does not provide any of this.
