### ISSUE TITLE
TableName() has no effect

### ISSUE THREAD

**Issue by kmergen** [yiisoft/active-record#291]
### What steps will reproduce the problem?
create ActiveRecord Class

### What is the expected result?
tableName should be different from className in this case my tableName is accotest

### What do you get instead?
Always className

### Additional info
I have this Entity class
```
final class Accomodation extends ActiveRecord
{

    public function tableName(): string
    {
        return 'accotest';
    }
}
```
My controller:
```
 // $query= $accomodation->instantiateQuery($accomodation::class);

        $acco = $arFactory->createAR(Accomodation::class);
        $query = $arFactory->createQueryTo(Accomodation::class);

        $model = $query->findOne(1);

        $acco->setAttribute('name', 'Haus Sonnenschein');
        $acco->setAttribute('category', 1);
        // $acco->save();

        return $this->viewRenderer->render('index', ['table' => null, '$model' => $model]);
```
I get the following error:

```
Yiisoft\Db\Exception\InvalidConfigException
The table does not exist: {{%accomodation}}

```
| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      |  8.1
| Operating system | Windows 11

**Comment by terabytesoftw** [comment]
Please change `tableName()` => `getTableName()`.

thks.
