### ISSUE TITLE
Yiiboot\ActiveRecord\ActiveRecord::populateRelation() not support the scalar type

### ISSUE THREAD

**Issue by niqingyang** [yiisoft/active-record#300]
### What steps will reproduce the problem?

When I implemented an aggregation query, the return value of the aggregation query was a scalar type. When I used `populateRelation` to populate the value, I found that it was not supported.

example:

```php

class User {
    public function getTagCount(): ActiveQuery {
        // ....
    }
}

$model = $arFactory->create(User::class);
$model->populateRelation('tagCount', 10);
```

### What is the expected result?

```php
echo $model->tagCount; // output 10
```

### What do you get instead?

```php
 Yiisoft\ActiveRecord\ActiveRecord::populateRelation(): Argument #2 ($records) must be of type Yiisoft\ActiveRecord\ActiveR
  ecordInterface|array|null, int given, called in ....
```

It is hoped that the type of the parameter $records of the method populateRelation of Yiisoft\ActiveRecord\ActiveRecordInterface can support the scalar type.

```php
// before
public function populateRelation(string $name, array|self|null $records): void;
// after or other better implementations
public function populateRelation(string $name, array|self|string|int|float|bool|null $records): void;
```

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 8.2
| Operating system | Windows11

**Comment by Tigrov** [comment]
Relations in DB means relations between table records (one to one, one to many, many to one, many to many).

Perhaps the issue is about a result of aggregate function `COUNT()`.

In this case you can do something like this

```php
class User {
    private int|null $tagCount = null;

    public function getTagCountQuery(): ActiveQuery
    {
        // ....
    }

    public function getTagCount(): int
    {
        if ($this->tagCount === null) {
            $this->tagCount = $this->getTagCountQuery()->scalar();
        }

        return $this->tagCount;
    }

    public function setTagCount(int $tagCount): void
    {
        $this->tagCount = $tagCount;
    }
}

$model = $arFactory->create(User::class);
$model->setTagCount(10);
```

**Comment by niqingyang** [comment]
I simplified the aggregate query in yii2, but encountered this problem when migrating the code of yii2 to yii3. In yii2, `populateRelation` has no type, so it supports scalars.

I defined a property Aggregate to collect the relationships of those aggregate queries, and then overridden `populateRelation` to be able to convert the results of the aggregate query to scalar or extract only part of the data when populating data. This is indeed no longer consistent with the relationship in the DB. It is good to keep it as it is now. I will try other solutions.

```php
#[\Attribute(\Attribute::TARGET_METHOD)]
class Aggregate
{
    public const Scalar = 0;
    public const One= 1;
    public const All= 2;

    public array $filter = [];

    public function __construct(array|string $filter = [], public int $type = Aggregate::Scalar)
    {
        $this->filter = (array)$filter;
    }

   // ....
}

class User {

   use AggregateActiveRecordTrait;

   public function getTags(): ActiveQuery {
       return $this->hasMany(Tag::class, ['user_id' => 'id']);
   }

   #[Aggregate('count')]
    public function getTagCount: ActiveQuery
    {
       return $this->getTags()->select(['user_id', 'count' => 'count(*)'])->groupBy(['user_id']);
    }
}

$query= $arFactory->createQueryTo(User::class);
$users = $query->with('tagCount')->all();

foreach($users as $user) {
    echo $user->tagCount; // echo every tagCount only by once tag count query
}
```
