### ISSUE TITLE
Remove the `ActiveRecord` prefix from events names

### ISSUE THREAD

**Issue by FabrizioCaldarelli** [yiisoft/active-record#31]
> Remove the `ActiveRecord` prefix from classes names

_Originally posted by @machour in https://github.com/yiisoft/active-record/pull/27_

If we use only InitEvent as name for event class, we could create a mess, for example for ActiveRecordInitEvent and ActiveQueryInitEvent, or between same event type but different base name classes.

**Comment by machour** [comment]
I can live with the ActiveRecord prefix if it's needed :)
