### ISSUE TITLE
Who can help me explain the current situation?

### ISSUE THREAD

**Issue by ak47f16200** [yiisoft/active-record#342]
yii3 active-record   Has the selection been completed? Can we send a formal version of Composer if it is completed? If not completed, what is the estimated time?

**Comment by Tigrov** [comment]
`active-record` is currently under development, backward compatibility may be broken at any time. Major changes will be made in the next 2-4 weeks, then we will see how it will work.

**Comment by ak47f16200** [comment]
> `active-record` is currently under development, backward compatibility may be broken at any time. Major changes will be made in the next 2-4 weeks, then we will see how it will work.

Okay, thank you. I have been using yii2 and its orm is very good. I have a new project and I still want to use it, but the integration of yii2 is too high and it is not easy to split. I hope Yii3 is even better. Let's release a version early and try it out
