### ISSUE TITLE
Rename `$attributes` to `$properties`

### ISSUE THREAD

**Issue by Tigrov** [yiisoft/active-record#343]
> @xepozz
> What's the reason to rename `attributes` to `properties`?

It was discussed that there is confusion between the `$attributes` AR property and PHP's `#[Attribute]`.

But it's a good question. Now this looks doubtful due to major changes and needs to be discussed again. Due to the renaming of public methods whose names contain `attribute`.

> @vjik 
> Are there any pitfalls here? Rename methods also it looks logically.

Now `property` name is already used in other methods

https://github.com/yiisoft/active-record/blob/090db08a3bb6833e0149bd9efd5aa521195270f7/src/BaseActiveRecordTrait.php#L275-L307

Currently `attributes` means column names in a table.
`properties` means properties of a class, wouldn't `properties` cause confusion similar to `attributes`.

`fields` is a more appropriate name, but it is also used for `ArrayableInterface`:

https://github.com/yiisoft/active-record/blob/090db08a3bb6833e0149bd9efd5aa521195270f7/src/BaseActiveRecord.php#L93-L108

If major changes involving method renaming are not a problem, then they should be separated into `names` and `values`:

* `attributes()` -> `names()` or `columnNames()` - column names
* `hasAttribute()` -> `has()` or `hasColumnName()` - if the column name exists
* `getAttributes()` -> `values()` or `data()` - get values of a row
* `getAttribute()` -> `get()` - get column value in a row
* `setAttribute()` -> `set()` - set column value in a row

And we should avoid `set` and `get` prefixes when declaring method names in base AR classes. These prefixes will be used to access values of a row e.g. `getName()`, `setName()`

**Comment by vjik** [comment]
Should there be a difference between class property values and column values from the user's point of view? Isn't that the same thing?

**Comment by Tigrov** [comment]
There is some chaos in this:
- `attributes()` - returns column names
- `getAttributes()` - returns values according to column names
- `$attributes` - a variable that stores the result of the selection. There may be not only table column values, but also other data returned along with the query (additional aggregate values and other).
- `getAttribute()` - returns the value from `$attributes` without checking the existence of the column

Column names and values can be accessed as class properties. But properties are not limited to column names. The class can contain any other properties. And if renaming `getAttributes()` to `getProperties()` the method will not return all class properties but only properties associated with column names.

We wanted to change the name to avoid confusion, but other confusion may arise.

**Comment by vjik** [comment]
So, there are:

- column names
- column values
- properties (column values + aggregate and other values)

right?

We can clearly name method: `getColumnNames()`, `getColumnValues()`, `getProperties()`, ...

**Comment by Tigrov** [comment]
(column values + aggregate and other values) stored in one place in `$attributes` property.
`getAttributes()`, `getAttribute()`, `setAttribute()` methods interact with `$attributes` property.

In addition, the user can define any other properties of the class.

What about a suggestion from the first message?

### previous name -> new name
* `attributes()` -> `names()` or **`columnNames()`** - column names
* `hasAttribute()` -> `hasName()` or **`hasColumnName()`** - if the column name exists
* `getAttributes()` -> `values()` or **`data()`** - get values of a row
* `getAttribute()` -> `get()` - get column value in a row
* `setAttribute()` -> `set()` - set column value in a row

and property `$attributes` rename to `$values` or **`$data`** according to the method name to **get values of a row**
