### ISSUE TITLE
Support relations via `array` type columns

### ISSUE THREAD

**Issue by Tigrov** [yiisoft/active-record#362]
Currently AR supports `scalar` to `array` relations:

`$this->hasMany(Item::class, ['id' => 'item_ids'])`

where `id` is `integer` column
and `item_ids` is `integer array` column

But AR does not support `array` to `scalar` relations
`$this->hasMany(Promotion::class, ['item_ids' => 'id'])`

The reason is in preparing the query condition. Currently it is only `IN` condition

https://github.com/yiisoft/active-record/blob/b000730e35c7dad0b6796bf0459c5fae017699d8/src/ActiveRelationTrait.php#L636

Which will generate condition like `id IN (1, 2, 3)`

But for `array` column this should be arrays overlap condition like `item_ids && ARRAY[1, 2, 3]` (Postgres)

To solve the issue it requires:
1. Realize `ArrayOverlapCondition` and `JsonOverlapCondition` (for json arrays) in db packages
2. Add `AR::columnType($columnName)` method to get type of the column
3. Prepare condition according to the column type:
```php
match ($columnType) {
    'array' => $this->andWhere(new ArrayOverlapCondition($attributes, $values)),
    'json' => $this->andWhere(new JsonOverlapCondition($attributes, $values)),
    default => $this->andWhere(['in', $attributes, $values]),
};
```

**Comment by samdark** [comment]
What's the support in other DBs?

**Comment by Tigrov** [comment]
> What's the support in other DBs?

* `Pgsql`, `Mssql`, `Oracle` support `arrays` but `db` package has realization only for `Pgsql`;
* `Mysql`, `Pgsql`, `Sqlite`, `Mssql`, `Oracle` support `json` but `db` package has realization only for `Mysql`, `Pgsql`, `Sqlite`.
But it may not be possible to implement `JsonOverlapCondition` for all DBMSs. At least for `Mysql` and `Pgsql` it is easy to implement.

**Comment by samdark** [comment]
If it's MySQL and PostgreSQL then it is worth doing.

**Comment by Tigrov** [comment]
Done with #375
