### ISSUE TITLE
Recurrent db parameter in ActiveDataProvider

### ISSUE THREAD

**Issue by fcaldarelli** [yiisoft/active-record#38]
When we create an ActiveDataProvider object, we have to always insert $db parameter, when it will be almost always Yii::$app->db.

https://github.com/yiisoft/active-record/blob/0fdc73d85755cc8903f8350c91e88c7dd6c0e0d4/src/data/ActiveDataProvider.php#L89

What do you think about changing the constructor to:

```php
public function __construct(QueryInterface $query, ConnectioInterface $db = null)
```

?

**Comment by samdark** [comment]
Setting it immediately makes sense.

**Comment by Tigrov** [comment]
Not relevant to the current implementation. Can be considered completed.
