### ISSUE TITLE
Any reason the library is using master version of yiisoft/db?

### ISSUE THREAD

**Issue by mtangoo** [yiisoft/active-record#384]
Is there any reason why in composer this library is using dev-master version of the `yiisoft/db` library and not the released version? It is not installable as it is as the mix happens until you constraint related dependencies to dev-master

**Comment by vjik** [comment]
This package will be depended from future major version of Yii DB, so currently `yiisoft/db:dev-master` is used.

**Comment by Tigrov** [comment]
You can temporarily install the `db` package by specifying in the composer require section:

`"yiisoft/db": "dev-master as 1.3.0",`

**Comment by mtangoo** [comment]
perfect. Thank you!
