### ISSUE TITLE
Getters and setters for Activerecord

### ISSUE THREAD

**Issue by Inkognitoo** [yiisoft/active-record#4]
If I understand correctly, here it is possible to leave wishes to the third version of the framework?

I very much need possibility to register the getter or the setter redefining default for any property of a model storing in a database
Now you have to do it through filters or afterFind(). This is not convient
That's how it looks like, for example, laravel: https://laravel.com/docs/5.6/eloquent-mutators#accessors-and-mutators

_____

Если я правильно понимаю, здесь можно оставить пожелания к третьей версии фреймворка?

Очень не хватает возможности прописать свой геттер или сеттер переопределяющий дефолтный для какого-то свойства модели хранящего в бд
Приходится изворачиваться через фильтры или afterFind
Вот так это выглядит например, у laravel: https://laravel.com/docs/5.6/eloquent-mutators#accessors-and-mutators

**Comment by samdark** [comment]
See https://github.com/yiisoft/yii2/pull/16496

**Comment by Tigrov** [comment]
It is okey to use user defined setters and getters in a project, for example `$model->getName()` and `$model->setName()`
This approach does not require extra magic.

**Comment by Tigrov** [comment]
Duplicate #18
