### ISSUE TITLE
add method that check is property was changed in ActiveRecord model

### ISSUE THREAD

**Issue by igorveremsky** [yiisoft/active-record#62]
I think it will be very helpful to implement in ActiveRecord method that return state that shows is property with some name was changed. Somethink like:
```php
public function isPropertyChanged($propertyName) {
	return ArrayHelper::keyExists($propertyName, $this->dirtyAttributes);
}
```

**Comment by Tigrov** [comment]
Done.

https://github.com/yiisoft/active-record/blob/41c66912b49aae072dd75dc6caee10c1c22ee1b0/src/BaseActiveRecord.php#L382-L393
