### ISSUE TITLE
TypeError BaseActiveRecord::findAll()

### ISSUE THREAD

**Issue by romkatsu** [yiisoft/active-record#86]
### What steps will reproduce the problem?

```php
Model::findAll(['id' => $id]);
```

### What is the expected result?

get ActiveRecordInterface

### What do you get instead?

```
TypeError: Return value of Yiisoft\ActiveRecord\BaseActiveRecord::findAll() must implement interface Yiisoft\ActiveRecord\ActiveRecordInterface, array returned
```

### Additional info

| Q                | A
| ---------------- | ---
| Version          | dev-master
| PHP version      |  7.4.3
| Operating system | Debian linux

**Comment by terabytesoftw** [comment]
You can write the code error, thanks.

**Comment by terabytesoftw** [comment]
Fixed, 

thks,
