### ISSUE TITLE
Can not call `ActiveRecord::all()` method with specified connection for database with different scheme

### ISSUE THREAD

**Issue by HaruAtari** [yiisoft/active-record#89]
I have two database connections. The main connection (`\Yii::$app->db`) is empty now. And the second which connected to a database with existed tables. Also I have an activeRecord model for an existed table from the second connection.

My code:

```
$connection2 = new Connection(/* ... */);
$connection2->open;
$records = MyActiveRecordModel::find()->all($connection2);
```

When I run it, I have an error: `The table does not exist: {{%my_active_record_model}}`. But how I said this table exists.

The method `\yii\db\Query::all()` takes data (rows) from the second database successfully. After that it try to populate records into activeRecord models. It calls `\yii\db\ActiveQuery::populate()` -> `\yii\db\ActiveQueryTrait::createModels()` -> `\yii\db\ActiveRecord::populateRecord()`. And here we have a problem.

This method takes a list of columns from the table schema from the `\Yii::$app->db` connections, but not from the connection, which was specified in `all()` call.

So I can't specify connection to take data from database with scheme different from the current connection.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.32
| PHP version      | any
| Operating system | any

**Comment by samdark** [comment]
Moved issue to standalone AR implementation. @HaruAtari if you know a good backwards compatible way to change it in Yii 2, let us know.

**Comment by brussens** [comment]
I certainly understand that the thoughts that came to my mind are an evil crutch, but nevertheless, this option is most likely to work (I have not checked). The idea is to throw the connection object through the entire method chain, up to `\yii\db\ActiveRecord::populateRecord()` to process the connection there as follows:

```php
public static function populateRecord($record, $row, $db = null)
 {
        $columns = static::getTableSchema($db)->columns;
        foreach ($row as $name => $value) {
            if (isset($columns[$name])) {
                $row[$name] = $columns[$name]->phpTypecast($value);
            }
        }
        parent::populateRecord($record, $row);
}
```

And already at `\yii\db\ActiveRecord`:

```php
public static function getTableSchema($db = null)
 {
        $db = $db ?? static::getDb();
        $tableSchema = $db
            ->getSchema()
            ->getTableSchema(static::tableName());

        if ($tableSchema === null) {
            throw new InvalidConfigException('The table does not exist: ' . static::tableName());
        }

        return $tableSchema;
 }
```
This way we can maintain backward compatibility, however, at the cost of the fact that in `\yii\db\Query::populate()` we will have a completely unnecessary parameter.

**Comment by samdark** [comment]
That won't be backwards compatible so can't be done in Yii 2. This way you will force updating all the AR classes that implement populateRecord or else you'll get an error:

```
Warning: Declaration of MyModel::populateRecord($record, $row) should be compatible with ActiveRecord::populateRecord($record, $row, $db = null)
```

**Comment by brussens** [comment]
Then one of the dirty options is to do something like that.

```php
class ActiveQuery
{
    protected $db = null;

    public function all($db = null)
    {
        $this->db = $db;
        return parent::all($db);
    }

    public function populateRecord($record, $row)
    {
        if ($this->db === null) {
             $modelClass = get_class($record);
             $modelClass::populateRecord($record, $row);
        } else {
            $columns = $this->db->getTableSchema()->columns;
            foreach ($row as $name => $value) {
                if (isset($columns[$name])) {
                    $row[$name] = $columns[$name]->phpTypecast($value);
                }
            }
            BaseActiveRecord::populateRecord($record, $row);
        }
    }
}
```

ActiveQueryTrait
```php
trait ActiveQueryTrait
{
    protected function createModels($rows)
    {
        if ($this->asArray) {
            return $rows;
        } else {
            $models = [];
            /* @var $class ActiveRecord */
            $class = $this->modelClass;
            foreach ($rows as $row) {
                $model = $class::instantiate($row);
                $this->populateRecord($model, $row);
                $models[] = $model;
            }
            return $models;
        }
    }
}
```

It's shameful, but it should solve the problem.

**Comment by Commifreak** [comment]
I still came across that issue:

Yii 2.0.47:

```
Projekt::find()
			                    ->asArray()
			                    ->one( $myDb);
```

The `Yii$app->db` does NOT have the whole table. But $myDb has.

But:

```
2023-05-25 14:15:02 [-][-][-][error][yii\base\InvalidConfigException]
yii\base\InvalidConfigException: The table does not exist: projekt in
/var/www/vendor/yiisoft/yii2/db/ActiveRecord.php:442
Stack trace:
#0
/var/www/vendor/yiisoft/yii2/db/ActiveRecord.php(513):
yii\db\ActiveRecord::getTableSchema()
#1
/var/www/vendor/yiisoft/yii2/db/ActiveQueryTrait.php(123):
yii\db\ActiveRecord::populateRecord()
#2
/var/www/vendor/yiisoft/yii2/db/ActiveQuery.php(219):
yii\db\ActiveQuery->createModels()
#3
/var/www/vendor/yiisoft/yii2/db/ActiveQuery.php(306):
yii\db\ActiveQuery->populate()
#4
/var/www/common/components/notification/NotificationInterface.php(314):
yii\db\ActiveQuery->one()
```

Whats the state of the "bug"?

**Comment by xepozz** [comment]
@Commifreak try ask in yii2 repo. this one for yii3

**Comment by Commifreak** [comment]
Ok, will do it. Just wondering, as the author was using Yii 2 as well.

**Comment by Tigrov** [comment]
Currently you can specify a db connection when create an `ActiveQuery` instance.

```php
$userQuery = new ActiveQuery(User::class, $db);
$users = $userQuery->all();
```

**Comment by Tigrov** [comment]
Now you can define method `withConnection()` inside the model and use it to change connection.

```php
$userQuery = new ActiveQuery((new User())->withConnection($db2));
$users = $userQuery->all();
```
